### ISSUE TITLE
对于源代码的建议

### ISSUE THREAD

**Issue by LasmGratel** [ustc-zzzz/fmltutor#1]
1. 仓库中含有大量不必要的文件（FML-XXX）等，甚至FML的changelog都扔进去了= =
2. README文件还是旧版本的，应重新写一个。
3. build.gradle还是用的特别老旧的mcp_mapping，为了跟上时代（大部分Mod）的脚步，请更新至stable_17或stable_18版。

**Comment by ustc-zzzz** [comment]
前两条已更新，第三条没有必要（我会在附录里给出mcp_mapping更新教程的）
已更新（Reika即视感→_→）
