### ISSUE TITLE
modid最好小写字母

### ISSUE THREAD

**Issue by yanshuicc** [ustc-zzzz/fmltutor#10]
私以为modid不仅仅使用字母，应该是最好使用小写字母。在mc(1.9.4)里面读取的modid文件夹的时候，会默认把大写变成小写，所以读取路径是小写的。一个小小坑。

**Comment by ustc-zzzz** [comment]
其实18x也有类似的问题，assets文件夹下的所有文件夹和文件都要是小写的。
![screenshot from 2016-06-12 13-44-45](https://cloud.githubusercontent.com/assets/8004211/15989224/ee6066d4-30a3-11e6-8063-40fd6d1dd5b4.png)
已更新。
