### ISSUE TITLE
如何进行反混淆代码

### ISSUE THREAD

**Issue by yanshuicc** [ustc-zzzz/fmltutor#14]
反编译就借助fernflower-fixed

```
java -jar fernflower-fixed.jar minecraft-xxx.jar ./output/
```

但是之后使用fields.csv、methods.csv、params.csv、以及*.srg的映射文件来进行反混淆该用什么工具的什么命令进行？

**Comment by taxerap** [comment]
你可以使用MCP帮你进行反混淆，.srg就是纪念曾经MCP领导人Searge（跑路去了打麻将）起的，里面都是一些field啊，什么的。
如果你想自己反混淆……先用记事本打开csv,然后另存为再用excel打开以免损坏。里面都是各种描述，比如fields.csv里面的就是对于成员变量的描述（参见wiki）
然后再按你的个人理解把它们翻译吧……工具就是你的大脑。

**Comment by yanshuicc** [comment]
好吧，其实我是想反混淆的不是mc的本体，反混淆mod。mcp应该不支持这个。我想多了。

**Comment by GWYOG** [comment]
反混淆mod的话使用immibis的[BON](https://github.com/immibis/bearded-octo-nemesis)就行了,不过现在倒是有人基于Forge Gradle做了[BON2](https://github.com/Parker8283/BON2)，比BON好用不少，反混淆效果也更好。

**Comment by yanshuicc** [comment]
自己写了个脚本。用field.csv和method.csv文件对fernflower-fixed反编译出来的代码做字符串替换。

**Comment by yanshuicc** [comment]
谢谢，最终自己写了个脚本。用field.csv和method.csv文件对fernflower-fixed反编译出来的代码做字符串替换。
