### ISSUE TITLE
为什么现在出教程都是1.8以上的呢

### ISSUE THREAD

**Issue by MeguminKato** [ustc-zzzz/fmltutor#17]
1.7.10这么多人用,开发1.8,1.9没地方用啊

**Comment by XiaoLingYYY** [comment]
等你学会了1.7.10他们就上去了吧

**Comment by cvrunmin** [comment]
现在最新版本(forge):1.10.2
1.7.10事实上已经落后3个主版本了
如果不是**大型Mod都卡在1.7.10**的话1.7.10的Mod在模组发布版算是过期了(都怪那些作者开这么大的坑，现在难倒自己了)

**Comment by MeguminKato** [comment]
是因为1.7.10里面某些功能在1.8+里面取消了?

**Comment by cvrunmin** [comment]
@q1051278389 在1.8开始材质设置被模型json取代，工程量極大

**Comment by XiaoLingYYY** [comment]
1.7.10还有坑爹的光照渲染。。。。。

**Comment by ustc-zzzz** [comment]
1.7.10是因为Mod数目众多导致的历史遗留，现在很多主流Mod都不愿意更新1.7.10版本了，更新也只是在修复BUG。
