### ISSUE TITLE
1.1中没有写清楚

### ISSUE THREAD

**Issue by dcsmf** [ustc-zzzz/fmltutor#18]
在“运行、构建和发布Mod的方法”上面6行的“然后打开IDE，将工程目录切换到这个目录”，其中“这个目录到底是什么没写清楚”，应该是把工程目录切换到mdk目录下的eclipse（或者idea）而不是mdk目录

**Comment by cvrunmin** [comment]
工程目录事实上不应切换到mdk目录，而是mdk目录的根目录 @ustc-zzzz 
在一般情況下只有mdk目录才存在工程文件

**Comment by ustc-zzzz** [comment]
我来说说我自己在我的Eclipse里是怎么做的：
`File => Import... => Existing Projects into Workspace => Next => Select root directory => Browse... => （mdk的上一级目录） => Projects => FMLTutor => Finish`
