### ISSUE TITLE
建议添加「将物品放入宝箱」条目

### ISSUE THREAD

**Issue by cvrunmin** [ustc-zzzz/fmltutor#19]
1.9前可以透过net.minecraftforge.common.ChestGenHooks.addItem(String,WeightedRandomChestContent)加入至宝箱。唯1.9后（包括1.9）使用LootTable机制，假如不直接修改档案便不能放入。（net.minecraft.world.storage.loot好像有有用的东西，但不知道怎么用）

**Comment by 3TUSK** [comment]
https://github.com/ForestryMC/ForestryMC/blob/mc-1.10/src/main/java/forestry/core/loot/LootTableLoader.java#L100
...

Edit:
`net.minecraftforge.event.LootTableEvent`

**Comment by cvrunmin** [comment]
不不不net.minecraftforge.event.LootTableEvent只在1.9.4之后才有的 @3TUSK

**Comment by 3TUSK** [comment]
1.9也在慢慢变成主流啊...

**Comment by ustc-zzzz** [comment]
已加入4.2节的计划。

**Comment by LasmGratel** [comment]
@3TUSK 不
是**`1.10.2`**
_2333_

**Comment by ustc-zzzz** [comment]
LG you a huge water B!
@LasmGratel

**Comment by MeguminKato** [comment]
@ustc-zzzz 2333

**Comment by 3TUSK** [comment]
@LasmGratel 
不，是`[1.10.2,)`

**Comment by sjx233** [comment]
Use `net.minecraftforge.event.LootTableLoadEvent`
[Loot Tables - Forge Documentation](http://mcforge.readthedocs.io/en/latest/items/loot_tables/) § Modifying Vanilla Loot

**Comment by Taskeren** [comment]
Emmmmmmm
催更、

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
