### ISSUE TITLE
请问FML没有相应的API文档么？

### ISSUE THREAD

**Issue by lzjohnny** [ustc-zzzz/fmltutor#2]
如果没有API文档的话，想要实现教程中没有的功能，只能去看源码么？另外感谢作者的教程~

**Comment by ustc-zzzz** [comment]
由于Mod和插件不同，插件因为只作用于服务端，可以有一套相对稳定的API，所以对应的JavaDoc也是配备得很齐全的，不过Mod往往需要修改的地方更多，所以说产生一套相对稳定的API就比较麻烦了，所以说丰富的JavaDoc也很难配齐，如果想要实现教程中没有的功能，也只能去看MCP或者一些成型Mod提供的源码了。其实教程的很大一部分也是通过源代码发掘出来的，不过本人把比较常用的整理了出来而已。
