### ISSUE TITLE
希望作者能将教程更新到1.10

### ISSUE THREAD

**Issue by a547673135** [ustc-zzzz/fmltutor#21]
希望作者能将教程里的版本更新到1.10，万分感谢～。
因为自己的网实在太差无法从forge服务器下载MDK所以不得不在mcbbs下了别人下载完的MDK，但是版本是1.10.2的。。。。
跟着教程学习的时候发现1.10和1.8已经有不小的区别了，比如说教程里的Material.ground在1.10里变成了Material.GROUND。this.setStepSound(soundTypeGrass)这句里soundTypeGrass找不到了（还好不很重要所以我删了这句话）。还有GameRegistry.registerBlock等方法不推荐使用了，doc里说使用register但我不知道怎么用。。。。。
另外我觉得教程写的很好，就是BlockState部分有点没看懂，准备再研究一下。

**Comment by 3TUSK** [comment]
``` java
GameRegistry.<Block>register(new Block(Material.IRON).setRegistryName("SampleBlock"));
GameRegistry.<Item>register(new Item().setRegistryName("SampleItem"));
```

**Comment by MeguminKato** [comment]
用idea,有forge mod构建向导,简单方便

**Comment by ustc-zzzz** [comment]
很抱歉，教程目前由于内容过多，如果向1.10（.2）迁移，势必会耗费作者的大量时间和精力，影响教程进度。
作者打算把教程写完然后更新针对1.10.2的内容。
