### ISSUE TITLE
关于Gradle一章的建议

### ISSUE THREAD

**Issue by LasmGratel** [ustc-zzzz/fmltutor#22]
> 我们注意到，和旧版本的MCP相比，新版本的MCP更加具体化了方法名，实际上，有的时候，MCP还会为部分方法指定了泛型。

建议在这一行后面加上：

> 你可以在[MCPBot(http://export.mcpbot.bspk.rs/)](http://export.mcpbot.bspk.rs/)获得1.7.10以上的所有MCP版本。

**Comment by ustc-zzzz** [comment]
LG you a huge water B!

**Comment by LasmGratel** [comment]
居然不虚心接受建议
你竟忘了_组织_的_铮铮教诲_![gg](https://ooo.0o0.ooo/2016/07/20/578f84611edad.png)
