### ISSUE TITLE
关于GitBooks的小问题

### ISSUE THREAD

**Issue by LasmGratel** [ustc-zzzz/fmltutor#23]
1. 左方除**Introduction**都是**中文**，改成**绪论**更_和谐_
2. 没有CSS _不科学,不和谐,不是人民期望的方向_ --- [Extend website and ebook style](https://starlying.gitbooks.io/gitbook-1/content/styling/book.html)

**Comment by ustc-zzzz** [comment]
LG you a huge water B!
Introduction我不知道怎么改
CSS我还是不知道怎么改
GG

**Comment by ustc-zzzz** [comment]
1. 已解决
2. 没有CSS明明才是人民期望的方向

**Comment by LasmGratel** [comment]
没有CSS~~(Counter-Strike Source) G胖~~读者会~~不会数3~~很不高兴的
2333
