### ISSUE TITLE
建议讲解 FMLEventChannel

### ISSUE THREAD

**Issue by 3TUSK** [ustc-zzzz/fmltutor#25]
没错，就是`net.minecraftforge.fml.common.network.FMLEventChannel`。
（虽然我大概知道怎么用，2333333333333333333333）

**Comment by MeguminKato** [comment]
@3TUSK 用法:System.exit(0);

**Comment by ustc-zzzz** [comment]
2333已收到，我考虑考虑加在3.3.x里。

**Comment by 3TUSK** [comment]
[`System.exit(0)`会被拦下的。](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/asm/transformers/TerminalTransformer.java)

**Comment by ustc-zzzz** [comment]
暂时先跳过这一节，会先把后续章节更完的。

**Comment by 3TUSK** [comment]
看样子可以考虑改天写个教程什么的...

**Comment by ustc-zzzz** [comment]
@3TUSK 2333快写我其实看着也一脸懵B然后也懒得翻现成mod的源码2333

**Comment by 3TUSK** [comment]
接不接Pull Request?

**Comment by ustc-zzzz** [comment]
@3TUSK 你自己独立写一篇吧= =

**Comment by 3TUSK** [comment]
喷
