### ISSUE TITLE
1.7 节的语言文件中没有添加Mod id

### ISSUE THREAD

**Issue by ustc-zzzz** [ustc-zzzz/fmltutor#26]
[1.7 节](https://ustc-zzzz.gitbooks.io/fmltutor/content/1.7-%E6%9C%AC%E5%9C%B0%E5%8C%96%E5%92%8C%E5%9B%BD%E9%99%85%E5%8C%96.html)中出现的代码：

```
item.goldenEgg.name=Golden Egg

tile.grassBlock.name=Grass Block
```

其中不包含Mod id的写法已被废弃，等待修改为：

```
item.fmltutor.goldenEgg.name=Golden Egg

tile.fmltutor.grassBlock.name=Grass Block
```

**Comment by myunco** [comment]
我加了mod id之后倒不显示名字了
不加mod id 正常显示

**Comment by 0f-0b** [comment]
@myunco `setUnlocalizedName("modid.itemName");`

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
