### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by ExtraMeteorP** [ustc-zzzz/fmltutor#3]
催更玩家NBT

**Comment by 3TUSK** [comment]
那不就是~~Capacity~~Capability吗...
顺带提一下以前的万恶IExtendedEntityProperties吧。

**Comment by ExtraMeteorP** [comment]
找到IEEP教程了，不催了

**Comment by ustc-zzzz** [comment]
@3TUSK IEEP准备提，不过Capability只有189有而1.8并没有让我感觉好方=_=||

**Comment by 3TUSK** [comment]
@ustc-zzzz 前缀：
`[1.8.9+专用] Capability`

**Comment by liach** [comment]
还有1.9也有cap

**Comment by ustc-zzzz** [comment]
嗯。。。我准备作为一个附章介绍一下，Capability确实很好用的样子。

**Comment by liqian2008** [comment]
写的非常好。精品教程。等待续作。最近看神秘时代5的代码，buildin资源加载obj模型文件，只能抄袭模仿，自己写差距还很大。renderer特效这些，好难啊，看别人代码都很吃力，不知道从哪里开始学。学了一阵java opengl，好难啊。

**Comment by ExtraMeteorP** [comment]
算了还是讲IEEP吧

**Comment by ustc-zzzz** [comment]
按照这个更新速度，我感觉猴年马月都讲不到IEEP。。。

**Comment by switefaster** [comment]
楼主，如何定义玩家模型的Entity

**Comment by ustc-zzzz** [comment]
@switefaster 开一个新Issue

**Comment by switefaster** [comment]
我自己学会了。。。

**Comment by ustc-zzzz** [comment]
现在教程正在向面向1.8.9迁移，IEEP什么的再也用不到了2333（不过猴年马月确实要过去了= =）

**Comment by ustc-zzzz** [comment]
Capability已更新：
https://ustc-zzzz.gitbooks.io/fmltutor/content/3.3.1-Capability%E7%B3%BB%E7%BB%9F%E4%B8%8E%E5%B7%B2%E6%9C%89%E5%AE%9E%E4%BD%93%E9%99%84%E5%8A%A0%E5%B1%9E%E6%80%A7.html
