### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by switefaster** [ustc-zzzz/fmltutor#30]
作者求你快点更新IGuiHandler的部分吧。。。

**Comment by cvrunmin** [comment]
差不多啦内心等一个礼拜（或更长）啦

**Comment by switefaster** [comment]
作者应该是到了周末才会更新吧……

**Comment by 3TUSK** [comment]
`IGuiHandler`实现起来不是十分困难啊...

**Comment by switefaster** [comment]
问题是IInventory每次都会崩溃，我也不知道Capability的物品槽怎么添加到GUI里=_=

**Comment by 3TUSK** [comment]
IInventory崩了是你的锅（雾），贴你的代码上来看看吧；
IItemHandler？用net.minecraftforge.items.SlotItemHandler………

**Comment by switefaster** [comment]
感谢大触为我解答

**Comment by ustc-zzzz** [comment]
GUI部分该更的都更完啦= =
