### ISSUE TITLE
請問 1.7.10 是不是沒有ModelLoader

### ISSUE THREAD

**Issue by Talesofwing** [ustc-zzzz/fmltutor#34]
請問 1.7.10 是不是沒有ModelLoader?

**Comment by ustc-zzzz** [comment]
应该是没有的。不过：

> 本教程不讨论1.8、1.7.10及之前的如1.7.2、1.6.4等Minecraft版本，虽然较1.8.9早期的版本的Mod开发和1.8.9的有着很多相通之处，本教程的很多地方也可能会对这些版本的Mod开发提供帮助，但本教程不去探究这些差别。
