### ISSUE TITLE
方法該在客戶端还是服務端執行?

### ISSUE THREAD

**Issue by Talesofwing** [ustc-zzzz/fmltutor#35]
像2.1.2的事件教程當中,
方塊激活化判斷

``` java
if (!event.isCanceled() && !worldIn.isRemote) {
     worldIn.setBlockToAir(pos);
     return true;
}
```

為什么要判斷要在客戶端上把方塊填空, 並且截斷事件??

**Comment by ustc-zzzz** [comment]
教程这里只是为了演示，因为把方块置为空气是一种较明显的响应效果。
如果事件被取消了方块就会置为空气，如果没有被取消就不会被置为空气。
然后因为游戏逻辑什么的都应当在服务端完成，所以这里还再加了一个判断。

**Comment by Talesofwing** [comment]
`world.IsRemote`
返回true 的話不是才是服務端嗎?? 
`! world.isRemote`
是指客戶端吧?
---- 上面的已經好了 ----

@ustc-zzzz 
world.setBlockToAir (pos); 只在服務端上執行的話
服務端會隔一段時間跟用戶端同步資訊嗎?
如果网絡卡頓的話, 是不是會造成 客戶端还沒有變成空氣方塊, 但實質服務端已經變成空氣方塊了?

**Comment by cvrunmin** [comment]
@Talesofwing 概念反轉了
根據Javadoc "True if the world is a 'slave' client; changes will not be saved or propagated from this world. For example, server worlds have this set to false, client worlds have this set to true."
world.isRemote=true是Client,false才是Server

**Comment by Talesofwing** [comment]
@cvronmin 好的 謝謝你

**Comment by liach** [comment]
@Talesofwing 

> world.setBlockToAir (pos); 只在服務端上執行的話
> 服務端會隔一段時間跟用戶端同步資訊嗎?

在呼叫方法后服务器会立刻给客户端发包裹，客户端会收到更新。

**Comment by Talesofwing** [comment]
@liach 好的感謝~
