### ISSUE TITLE
2.3.3 藥水效果 (1.7.10)

### ISSUE THREAD

**Issue by Talesofwing** [ustc-zzzz/fmltutor#36]
在1.7.10中 構造方法是傳入ID (int) 而不是名字
我傳入了36會崩潰 (可能因為原本是沒有此ID的)
我傳入了20 (原版為凋零的效果)後, 會和凋零重疊了...
請問1.7.10要怎麼做?

**Comment by liach** [comment]
先用Reflection开大数组到255，然后你就可以传入36了。

**Comment by 0f-0b** [comment]
就用它了：[附录C 混淆与反射](https://ustc-zzzz.gitbooks.io/fmltutor/content/附录C-混淆与反射.html)

**Comment by Talesofwing** [comment]
@liach 原來是因為一開始的數組大小沒去到36 嗎
我去試試先

**Comment by Talesofwing** [comment]
@sjx233 还沒有看到那麼後呢=.=
