### ISSUE TITLE
2.4.1 熱鍵 (对不起, 又是我, 可能版本不同所以問題比較多=.=)

### ISSUE THREAD

**Issue by Talesofwing** [ustc-zzzz/fmltutor#37]
FMLCommonHandler.instance().bus().register(this);

我在1.7.10中要加入这個才能觸發那個Input Event,
在高版本中是不需要的嗎?

**Comment by liach** [comment]
对。因为高版本里面这两个EventBus合并了，而1.7没有

**Comment by Talesofwing** [comment]
@liach 大佬这么晚还沒睡嗎! 好的謝謝你
