### ISSUE TITLE
1.10.2中 getItemFromBlock(block) 得到null值的问题

### ISSUE THREAD

**Issue by CatMe0w** [ustc-zzzz/fmltutor#39]
我在1.10.2中编写mod时，已经注册过方块的ItemBlock，在为方块添加模型和材质时使用的getItemFromBlock(block)方法得到null值，导致游戏出现NullPointerException。
同时getBlockRegistry()也已被弃用。
求解啦。

**Comment by liach** [comment]
方块的注册表是在`Block`类里面的。或者你可以在注册后保留方块实例，里面再保留个物品实例即可。

**Comment by 3TUSK** [comment]
@ustc-zzzz 就不能提一下那个神奇的`GameRegistry.<T extends IForgeRegistry<T>>register(T objToReg)`吗...

**Comment by liach** [comment]
@3TUSK Unfortunately, 1.8.9 is way too old. The guide should move to minecraft 1.11.

**Comment by 3TUSK** [comment]
... @liach 给他点时间shift

**Comment by CatMe0w** [comment]
yep

**Comment by CatMe0w** [comment]
改动的东西应该不会太多（相对于1.10而言），不过forge官方的文档真是简陋的过分。。。
anyway，期待新版本的教程，拭目以待吧

**Comment by liach** [comment]
@CatMe0w minecraft的代码本来就是靠你自己去领悟的。官方文档等待着贡献者呢。javadoc也不全。

**Comment by 3TUSK** [comment]
Minecraft代码（不含FML等硬插进去的成分）分明是没有javadoc然后让别人去猜

回到正题。Item类下有一个专门注册ItemBlock的protected方法，不知道当时那个写protected的人在想什么- -

**Comment by EntropyIncreaser** [comment]
通过`getBlockRegistry`获得`ResourceLocation`可以直接`block.getRegistryName()`来解决

**Comment by 3TUSK** [comment]
@ustc-zzzz 你要是在的话，把这个issue关了吧...

`getBlockRegistry()` -> `Block.REGISTRY`

**Comment by liach** [comment]
应该用`ForgeRegistries.BLOCK`

**Comment by ustc-zzzz** [comment]
在6月28号的提交中，已经使用`getRegistryName`/`setRegistryName`替代了之前直接在注册时传入参数的注册方式。
