### ISSUE TITLE
支持大佬~

### ISSUE THREAD

**Issue by Mileber** [ustc-zzzz/fmltutor#40]
话说infinity studio还招人嘛？最近在学习mod开发，Java基础觉得还可以，想向大佬们学习QAQ。。。

**Comment by ustc-zzzz** [comment]
一直在招人，不过最近审核员等都比较忙，所以可能通过审核要等一阵子。

**Comment by liach** [comment]
呵呵……

**Comment by 3TUSK** [comment]
标签错了吧这...这哪是教程的疑问了...

**Comment by liach** [comment]
Is here being an advertisement site for InfStudio?

**Comment by ustc-zzzz** [comment]
In fact, @liach 
![screenshot from 2016-12-09 17-47-14](https://cloud.githubusercontent.com/assets/8004211/21055993/a859005c-be6e-11e6-96c5-2f67e8b75a45.png)
The advertisement has already been there for a long time.

**Comment by liach** [comment]
不知道为什么，是不是inf的全是学霸，没空编写mod或者给forge贡献。inf招人不是在mcbbs和qq上吗？

**Comment by ustc-zzzz** [comment]
那我不客气了。
@liach 

一、首先，至少目前而言，GitHub没有删除Issue的按钮吧？如果遇到有人问和教程内容不相关的问题，换作你，你是希望先骂他一通然后再嘲讽他一通呢，还是先和和气气地试着回答他一下他的问题，或者为他的回答指明一条方向呢？我回答完了也当场关闭了Issue吧？

二、这个项目没有过于严格的非商业性质吧，版权声明写着CC-BY-SA 4.0没有NC这两个字母吧，更何况InfStudio是非营利小组，所以就算我打广告也不过分吧？更何况我只在版权声明里注明了一下，这个Issue提到InfStudio只是我意料之外的事情。InfStudio招人确实只在MCBBS和QQ上没错。

三、InfStudio写的Mod虽然小，名气不高（一些诸如Custom Skin Loader或者Unicode Font Fixer的Mod真的名气不高吗），但是也在不断产出独立的项目吧？当然，像InfStudio这种过气Mod小组，估计也承受不起你这种到处给别人的项目发Issue发Pull Request的大佬。

综上，你开心就好。
