### ISSUE TITLE
1.10.2 是否能添加相关的注明

### ISSUE THREAD

**Issue by nekomeowww** [ustc-zzzz/fmltutor#41]
在1.9的时候，    
```net.minecraft.client.resources.model.ModelResourceLocation```
被移动到了    
```net.minecraft.client.renderer.block.model``` 下面

**Comment by ustc-zzzz** [comment]
教程本身是面向1.8.9的，所以说因为文章结构原因，不大容易在其中加入关于1.9.4/1.10.2的代码细节。
不过作者欢迎读者在Issue等处进行1.9.4/1.10.2的代码差别讨论。

**Comment by 3TUSK** [comment]
这种东西其实让IDE自动帮你找也可以吧...

**Comment by nekomeowww** [comment]
这样，嘛只是说明一下啦233
不过教程不错（感谢X3）
@3TUSK 关于IDE的话，eclipse没有说，我是去forge的forum搜索看到这个变动的。

**Comment by 3TUSK** [comment]
诶？删掉报错的导入再重新让Eclipse搜索不行吗？
> 这不是明摆着逼人换Intellij嘛

And now I will kill off all notificiation

**Comment by liach** [comment]
intellij的确比eclipse有优势，尤其是在出了https://github.com/minecraft-dev/MinecraftDev 这个idea插件后，更加方便。

**Comment by WAAutoMaton** [comment]
而且有不少教程里使用的1.8的方法在1.10的doc里被标记为不推荐使用了

**Comment by liach** [comment]
那些方法已经转移到`BlockStateContainer`里面了。
