### ISSUE TITLE
关于Gradle的建议

### ISSUE THREAD

**Issue by LasmGratel** [ustc-zzzz/fmltutor#43]
应该在设置工作空间那里建议国内用户直接使用Gradle而不是gradlew gradlew慢到爆
然后给出一个下载地址

**Comment by ustc-zzzz** [comment]
拒绝，安装Gradle会带来额外的学习成本，同时Gradle Wrapper是目前很多mod项目的标配

**Comment by LasmGratel** [comment]
学习什么？modder不会把gradle bin加入path？
看到很多人卡在gradle wrapper的下载上很是蛋疼

**Comment by NekoCaffeine** [comment]
Gradle Wrapper多好x

**Comment by NekoCaffeine** [comment]
自备梯子是开发者的必修课

**Comment by ustc-zzzz** [comment]
如果对Gradle Wrapper感到不满，开发者会自己寻求下载安装Gradle的方式。另外，目前大部分国内开发者都是卡在下载mc/forge相关的文件上，几乎没有卡在下载Gradle Wrapper的

**Comment by LasmGratel** [comment]
那么可以加上建议使用bangbang93的repo来替代forge repo吗？
毕竟翻墙工具不是人人都有

**Comment by chawyehsu** [comment]
说个“笑话”，即时设置了 proxy 第一次下载 `gradle-x.x-bin.zip` 时也会慢出翔，手动下载 zip 包比啥都来得爽。但却解决不了下载 mc/forge 相关文件的问题，所以还是回到 `no proxy no programming, inside gfw.`。

也所以才会有 bangbang93 / FGOW 之类“节省开发者生命”的项目。不过比起这些，个人觉得配免翻墙工作环境并不比下个 xx-net 再来一句 `./gradlew setupDecompWorkspace -Dhttp.proxyHost=<host> -Dhttp.proxyPort=<port>` 来得简单，如果翻墙必修课没学会的话。。

离题了:new_moon_with_face:
