### ISSUE TITLE
教程1.2主类、代理和mod信息，有个疑问

### ISSUE THREAD

**Issue by myunco** [ustc-zzzz/fmltutor#48]
新建一个包（这里是com.github.ustc_zzzz.fmltutor），并在其中新建一个类（强烈建议这个类的类名和你的Mod名称相同），这就是这个Mod的主类了。

把下面的代码抄进你新建的类中，下面我会解释为什么要这么做。

我把代码抄进去后 第三行：
import com.github.ustc_zzzz.fmltutor.common.CommonProxy;
提示：无法解析导入 com.github.ustc_zzzz.fmltutor.common
用的是eclipse。
类名包名都是照着你教程来的 其他地方没错误
这是怎么回事

**Comment by myunco** [comment]
难道不能用eclipse

**Comment by cvrunmin** [comment]
Missing class com.github.ustc_zzzz.fmltutor.common.CommonProxy
You SHOULD read the whole tutorial (at least the whole 1.2 part) before asking this question
遗失com.github.ustc_zzzz.fmltutor.common.CommonProxy类
你**应该**在发问前阅读整个教程（至少整个1.2部分）

**Comment by NekoCaffeine** [comment]
这算是基础的IDE使用问题，十分反对没有基础上来就写mod的modder
