### ISSUE TITLE
添加EnumHelper和ReflectionHelper的用途

### ISSUE THREAD

**Issue by liach** [ustc-zzzz/fmltutor#5]
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/relauncher/ReflectionHelper.java

https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/util/EnumHelper.java

**Comment by liach** [comment]
关于最新教程3.1.3中的自然生成：
EnumHelper可以用来添加EnumCreatureType，或者实体生物的生成类型
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/util/EnumHelper.java#L69

**Comment by ustc-zzzz** [comment]
唔。。。其实我刚刚看了看，EnumHelper可以用来添加EnumCreatureType这一点觉着好像没什么用的样子，用的Mod也不是很多对吧～
https://github.com/search?l=java&q=EnumHelper.addCreatureType&ref=searchresults&type=Code

**Comment by ustc-zzzz** [comment]
https://github.com/ustc-zzzz/fmltutor/wiki/%E9%99%84%E5%BD%95%E4%B8%89-%E6%B7%B7%E6%B7%86%E4%B8%8E%E5%8F%8D%E5%B0%84
其中包含了EnumHelper和ReflectionHelper。

**Comment by liach** [comment]
呃……不用这样大动干戈找三种名称的转换，只要用https://github.com/bspkrs/mcpmappingviewer 这个工具就好了，只是注意用的时候最好用代理。
