### ISSUE TITLE
简化BlockState映射后出现显示问题

### ISSUE THREAD

**Issue by switefaster** [ustc-zzzz/fmltutor#50]
由于不知如何定义display项，所以方块在手上第三人称时会变得无比巨大

**Comment by 3TUSK** [comment]
zzzz写这个之前的话，minecraftwiki反倒成最合适的资料了...去中文minecraftwiki搜“模型”。

**Comment by switefaster** [comment]
@3TUSK 我是用了forge_marker之后没法写itemmodel导致的，请问怎么追加itemmodel的内容？

**Comment by 3TUSK** [comment]
http://minecraft-zh.gamepedia.com/%E6%A8%A1%E5%9E%8B#Item_models

0.确定你已经读过相关教程章节
1.`ModelLoader.setCustomModelResourceLocation(Item item, int metadata, ModelResourceLocation mrl)`
2.让物品模型“继承”方块模型
3.说了去Minecraftwiki...然后按给的范例加`display`标签然后慢慢调

**Comment by 3TUSK** [comment]
呃，重新看了一眼教程——请不要使用`default`标签来定义模型！

Appendix: 准确地说，是这样：
````javascript
//GitHub的Markdown代码块语法高亮不允许JSON使用//加注释，所以，这其实是JavaScript的语法高亮
{
    "forge_marker": 1,
    "variants": {
        "inventory": [{ }],
        // PropertyBool.create("working");
        "working": { //注意下面的true和false一定要用引号括起来
            "true": { "model": "example_mod:example_model" },
            "false": { "model": "example_mod:example_model_inactive" }
        }
    }
}
````

**Comment by liach** [comment]
json用`“_comment:” ""`评论

**Comment by 3TUSK** [comment]
拒绝

**Comment by switefaster** [comment]
谢了

**Comment by 3TUSK** [comment]
@ustc-zzzz 是不是该关了？

**Comment by switefaster** [comment]
是该关了

**Comment by 3TUSK** [comment]
倒是点一下Close Issue啊- -
