### ISSUE TITLE
初始化ToolMaterial感觉可以放进ConfigLoader里

### ISSUE THREAD

**Issue by FirokOtaku** [ustc-zzzz/fmltutor#52]
教程里是在对应工具的class内创建了材质
`public static final Item.ToolMaterial NAME_MATERIAL= EnumHelper.addToolMaterial("NAME_MATERIAL", 3, 16, 16.0F, 0.0F, 10);`
然后调用了super()初始化

但是这样每一种工具都会运行一遍同样的代码吧..

如果把初始化工具材质的代码放在一起
比如放进ConfigLoader内 然后再
`super(ConfigLoader.NAME_MATERIAL ,8.0F,-3.1F);`

这样应该效率更高而且更便于管理材质属性

**Comment by 3TUSK** [comment]
这是一个见仁见智的问题...

**Comment by ustc-zzzz** [comment]
如楼上所言。。。真正的mod代码结构完全应该由开发者自己设计。
我为什么要在教程里这么做？因为这么做看着清晰，另一部分也只是历史遗留原因。
