### ISSUE TITLE
催更&教程建议

### ISSUE THREAD

**Issue by switefaster** [ustc-zzzz/fmltutor#53]
若渲染部分过难，是否可以将世界生成提前？

**Comment by 3TUSK** [comment]
~~渲染部分建议直接不讲，直接说买本 OpenGL 的书看（笑）~~

**Comment by switefaster** [comment]
可以啊233 @3TUSK

**Comment by 0f-0b** [comment]
同是来催更的
~~其实是在跟着此1.8.9的教程做1.12的Mod~~

**Comment by 3d-pinball** [comment]
催更
我是跟着做1.7.10的mod
想看世界生成啊

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
