### ISSUE TITLE
想請問怎麼做「有害的」葉水效果。

### ISSUE THREAD

**Issue by nevikw39** [ustc-zzzz/fmltutor#54]
首先十分感謝版主的教學。然而，這裡僅有無害的藥水。想請問一下，如何做出類似傷害葉水般，定時產生傷害的藥水？

**Comment by ustc-zzzz** [comment]
你可以监听玩家每个tick都会触发的事件，然后检查玩家身上是否有药水效果，从而决定玩家是否受到伤害。

**Comment by 0f-0b** [comment]
重写 `Potion::performEffect` `(Lnet/minecraft/entity/EntityLivingBase;I)V`
和 `Potion::isReady` `(II)Z`

**Comment by ustc-zzzz** [comment]
emmm，听楼上的
