### ISSUE TITLE
有人知道 1.12 新的註冊機制如何使用嗎？

### ISSUE THREAD

**Issue by nevikw39** [ustc-zzzz/fmltutor#55]
這是我的 code ：
```
public class ItemLoader {
	
	public static final Item itemS = new ItemS();
	
	@SubscribeEvent
	public static void registerItem(RegistryEvent.Register<Item> event)
	{
		IForgeRegistry<Item> registry = event.getRegistry();
		registry.register(itemS.setRegistryName("s"));
	}
}
```
然而，卻沒出現在遊戲中。有點想回去 1.11 算了~

**Comment by 0f-0b** [comment]
在 `FMLPreInitializationEvent` 时使用`MinecraftForge.EVENT_BUS.register(new ItemLoader())`, 或者用 `@Mod.EventBusSubscriber`

**Comment by liach** [comment]
eventbus 注册最好在 FMLConstuctionEvent 或者 PreInit 时注册。可以直接给 ItemLoader 加 `@EventBusSubscriber`

**Comment by sjx233** [comment]
[FMLConstuctionEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/event/FMLConstructionEvent.java#L29) 的 Javadoc 里写着：
> Should not be used by mods.

**Comment by liach** [comment]
这个至少是 static {} 和 ctor 呼叫后呼叫的，比较安全

**Comment by nevikw39** [comment]
謝謝大家，我盡快來試！

**Comment by nevikw39** [comment]
在 preInit 事件中加入：
`MinecraftForge.EVENT_BUS.register(new ItemLoader());`
後，就成功了！！！
感謝大家熱心地回答！
