### ISSUE TITLE
动物幼崽的材质会使用原版

### ISSUE THREAD

**Issue by ssr1353359550** [ustc-zzzz/fmltutor#57]
作者大大，为什么动物幼崽的材质会使用原版
比如这样↓↓↓
![2017-07-17_13 57 29](https://user-images.githubusercontent.com/27810601/28256880-e9599e5e-6af8-11e7-8302-fa69682b8e13.png)
而且在对造型与某一种原版动物一样的动物做实体生物的内禀运动属性时可以直接用“ModelPig”这种类
比如这样↓↓↓
public RenderVegetablePig(RenderManager renderManager)
    {
        super(renderManager, new ModelPig(), 0.5F);
    }
还有作者的邮箱没用啦！！！（这个→zzzz@infstudio.net）

**Comment by switefaster** [comment]
额这主要是因为继承了EntityPig,Pig的繁殖行为诞生的是EntityPig而不是你的Entity类,建议重写相应部分。如果改动较大,建议继承EntityMob从0写起

**Comment by ccicnce113424** [comment]
Override繁殖部分
