### ISSUE TITLE
网站打开很慢

### ISSUE THREAD

**Issue by yksalun** [ustc-zzzz/fmltutor#59]
网站打开很慢，就这两天开始的。
![image](https://user-images.githubusercontent.com/7500277/28347016-3312cd3a-6c67-11e7-9543-29da9bc152be.png)
打开之后只显示上图这些信息

**Comment by sjx233** [comment]
\[[https://fmltutor.ustc-zzzz.net](https://fmltutor.ustc-zzzz.net)\]
我打开没问题

**Comment by ustc-zzzz** [comment]
emmm，教程是挂在GitBook上的，网站访问速度问题也只是天命，实在不行的话挂个代理吧2333
