### ISSUE TITLE
添加Capability和IItemHandler用途

### ISSUE THREAD

**Issue by liach** [ustc-zzzz/fmltutor#6]
https://github.com/MinecraftForge/MinecraftForge/tree/master/src/main/java/net/minecraftforge/common/capabilities

https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/items/IItemHandler.java

**Comment by ustc-zzzz** [comment]
教程目前正在向1.8.9推进，准备放弃1.8部分。

**Comment by cvrunmin** [comment]
不，你该直接上1.9 XD

**Comment by ustc-zzzz** [comment]
194变化的东西太多= =准备先把189写完了再上194的= = @cvronmin

**Comment by ustc-zzzz** [comment]
IItemHandler已讲：
https://github.com/ustc-zzzz/fmltutor/wiki/3.2.2-TileEntity%E4%B8%8E%E6%95%B0%E6%8D%AE%E6%9B%B4%E6%96%B0

**Comment by ustc-zzzz** [comment]
Capability已更新：
https://ustc-zzzz.gitbooks.io/fmltutor/content/3.3.1-Capability%E7%B3%BB%E7%BB%9F%E4%B8%8E%E5%B7%B2%E6%9C%89%E5%AE%9E%E4%BD%93%E9%99%84%E5%8A%A0%E5%B1%9E%E6%80%A7.html
