### ISSUE TITLE
别偷懒啊

### ISSUE THREAD

**Issue by NekoCaffeine** [ustc-zzzz/fmltutor#62]
上次那个IEnergyEmitter还存不存在于被处理过后的字节码的问题还没搞清楚你怎么就跑路了

**Comment by 3TUSK** [comment]
[不存在。](https://github.com/MinecraftForge/MinecraftForge/blob/1.8.9/src/main/java/net/minecraftforge/fml/common/asm/transformers/ModAPITransformer.java)

以及 Delegation Pattern 欢迎你

**Comment by NekoCaffeine** [comment]
因为上次4z给的字节码里面是存在的，总感觉收集的方式有问题

**Comment by 3TUSK** [comment]
> 上次4z给的字节码里面是存在的

zzzz 有没有给你他收集字节码的方式，如果有，你按照这个方式能否复现。
