### ISSUE TITLE
2.5.1 世界生成

### ISSUE THREAD

**Issue by pluiedev** [ustc-zzzz/fmltutor#69]
```java
 BiomeGenBase biomeGenBase = world.getBiomeGenForCoords(blockpos);
```
在1.12下 `world.getBiomeGenForCoords(BlockPos)`已经被更改成`world.getBiome(final BlockPos)` 返回`Biome`对象
所以应该改成
```java
Biome biomeGenBase = world.getBiome(blockpos);
```
至于之后的`biomeGenBase.getIntRainfall();`
现在的Biome类已经没有`getIntRainfall()`这个方法了
应该用`Biome.getRainfall() * 65536`

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
