### ISSUE TITLE
让Minecraft连接实体积木

### ISSUE THREAD

**Issue by gawen1** [ustc-zzzz/fmltutor#70]
同学你好，我们是深圳的一个初创团队，我们在做一个Minecraft开发项目，想实现我们的智能积木和Minecraft世界连接，并定义各种有趣的玩法，想邀请你加入我们的开发计划。这是我们的项目简介：http://www.logitow.com/index.php?s=mod

**Comment by liach** [comment]
Minecraft电脑版和ios安卓没什么大联系啊

**Comment by 0f-0b** [comment]
~~感觉和Forge支持蓝牙那个issue有关系~~

**Comment by pluiedev** [comment]
这是个issue么...
即使是个issue那也跟这个教程无关吧...

/自行PM

**Comment by gawen1** [comment]
感兴趣的同学可以联系我，我们想要更多的小伙伴一起开发这个项目，我们硬件API是免费开源的。
