### ISSUE TITLE
补充（对于java 1.9+）

### ISSUE THREAD

**Issue by JiyuanChen** [ustc-zzzz/fmltutor#71]
当java版本为1.9.0或更高时，在配置工作环境中"./gradlew setupDecompWorkspace" 会提示
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.`

解决方法（来自https://stackoverflow.com/questions/46867399/react-native-error-could-not-determine-java-version-from-9-0-1）:
将`./gradle/wrapper`下的`gradle-wrapper.properties`中`distributionUrl` 配置为`distributionUrl=https\://services.gradle.org/distributions/gradle-4.3-rc-2-all.zip`
………………
但是forgeGradle并不支持Java 1.9

**Comment by sjx233** [comment]
Markdown不是这么用的吧……
code block用
```markdown
    ```
    // code block here
    ```
```
（此评论 _可能_ 会在问题修复后删除）

**Comment by 3TUSK** [comment]
为什么要使用 Java 9 开发 Mod？MinecraftForge 有极少数关键功能依赖具体的 JVM 实现，短时间内不可能兼容 Java 9 的...

建议关闭此 issue。

**Comment by 0f-0b** [comment]
MinecraftForge/MinecraftForge#3935

**Comment by ustc-zzzz** [comment]
已于 03066dac25c3dbc79fb204304a361480a3d753ed 添加。
