### ISSUE TITLE
Kotlin编写Mod

### ISSUE THREAD

**Issue by HoshinoTented** [ustc-zzzz/fmltutor#73]
Kotlin已经有Gradle支持了, 也可以写Mod了
所以。。
附录E要改一下？

**Comment by 3TUSK** [comment]
> 不过Forge本身目前还没有提供相应的支持。

你大概需要若干 Kotlin 的标准库，但 Forge 并不自带这些库。我推荐直接依赖 [ShadowFacts' Forgelin](https://github.com/shadowfacts/Forgelin)。

再说了，Forge 已经有取消自带 Scala 库的计划了...

**Comment by HoshinoTented** [comment]
但是可以通过Gradle导入Kotlin标准库, 这并不会消耗很多时间
在build.gradle添加以下代码
```Gradle
buildscript {
    ext.kotlinVersion = '1.2.30'
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

apply plugin: 'kotlin'

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
}
```

**Comment by HoshinoTented** [comment]
//Kotlin标准库本身也不算很多

**Comment by 3TUSK** [comment]
> 但是可以通过Gradle导入Kotlin标准库, 这并不会消耗很多时间

你考虑过玩家运行时找不到类游戏崩溃的感受吗.kt？

**Comment by ccicnce113424** [comment]
看forge是否开放kotlin的api

**Comment by ccicnce113424** [comment]
虽说java和Kotlin是兼容的，但是目前为止forge还没有放出Kotlin的api

**Comment by HoshinoTented** [comment]
emmm Kotlin的api指什么emmm
高阶函数支持？

**Comment by 3TUSK** [comment]
@HoshinoTented Forge 不自带 Kotlin 标准库。事实上也不可能会自带... 取消自带 Scala 标准库已经成定论了，只是时间问题。

**Comment by HoshinoTented** [comment]
那也可以自己写个jar任务然后把标准库打进去吧emmmmm

**Comment by 3TUSK** [comment]
https://minecraft.curseforge.com/projects/shadowfacts-forgelin
现在通常的做法是使用类似这样的 Mod 以避免冲突。

**Comment by ustc-zzzz** [comment]
由于本人对Kotlin了解不深，无法完成这一部分，如有人感兴趣，可以向`book`分支发PR投稿（记得放在附录里）。
