### ISSUE TITLE
Item手持和掉落都变得很大, 但Block不会

### ISSUE THREAD

**Issue by HoshinoTented** [ustc-zzzz/fmltutor#75]
没错又是我，问题少女（逃
![image](https://user-images.githubusercontent.com/25280943/40166241-ab047042-59f0-11e8-9296-712866bdccb0.png)

**Comment by HoshinoTented** [comment]
mcversion: 1.12.2
repo: https://github.com/HoshinoTented/Mod-1.12.2

**Comment by 0f-0b** [comment]
Minecraft 1.9 开始物品模型分左右手了
所以最有效的方法就是把 `"display": { ... }` 删掉
或者 [Model § Item models](https://minecraft.gamepedia.com/Model#Item_models)

**Comment by HoshinoTented** [comment]
删掉display。。似乎没什么效果
然后wiki又看不懂
我好菜

**Comment by 0f-0b** [comment]
把 `"builtin/generated"` 改成 `"item/generated"` 试试看？

**Comment by HoshinoTented** [comment]
dalao
