### ISSUE TITLE
Gradle配置技巧的错误

### ISSUE THREAD

**Issue by liach** [ustc-zzzz/fmltutor#8]
``` gradle
minecraft {
    replace "@version@", project.version
}
```

ForgeGradle有问题，这个`replace`不能正常工作。希望您将这段移除。

**Comment by ustc-zzzz** [comment]
经过检查和测试，在构建后的Mod Jar中发现`@version@`字段已被正常替换，恕作者没能发现问题在哪里。
![difference](https://cloud.githubusercontent.com/assets/8004211/14790851/c148d268-0b45-11e6-88dd-15b9b4807aee.png)
左边的是主类源码，右边的是构建后在`build/libs`文件夹下的`fmltutor-1.0.0-sources.jar`内的主类代码。

**Comment by liach** [comment]
mcmod.info中呢?

**Comment by ustc-zzzz** [comment]
也是被替换掉的。
