### ISSUE TITLE
事件列表中“当玩家登出时触发。”事件拼写错误

### ISSUE THREAD

**Issue by MlgmXyysd** [ustc-zzzz/fmltutor#80]
[F] PlayerEvent.PlayerLoggeOutEvent extends PlayerEvent
应该为
[F] PlayerEvent.PlayerLoggedOutEvent extends PlayerEvent

**Comment by MlgmXyysd** [comment]
@ustc-zzzz

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新（事件列表已从附录中删除），请检索仍在更新的教程。
