### ISSUE TITLE
Shadowsocks代理服务器失效了，无法使用

### ISSUE THREAD

**Issue by wdog5** [ustc-zzzz/fmltutor#83]
Shadowsocks代理服务器失效了，无法使用

**Comment by Srar** [comment]
Hi! 我是代理服务器的提供者, 目前我已经开启Shadowsocks访问记录日志, 请重新使用代理服务器再次构建一遍以便方便我定位问题. 还需要您向我的邮箱(a1020938070@gmail.com)发送您的IP以供定位.
