### ISSUE TITLE
关于SRG名的查询

### ISSUE THREAD

**Issue by kaaass** [ustc-zzzz/fmltutor#85]
其实MCP搞过一个带GUI的MCP-SRG名查询工具，叫[MCP Mapping Viewer](https://github.com/bspkrs/MCPMappingViewer)。MCP开发包里也自带了。

不过这个工具也是有些缺点的，比如mapping龟速下载。解决方法是自己下载zip并处理，处理过程略麻烦，可以把我附件的[1.12.zip](https://github.com/ustc-zzzz/fmltutor/files/2255931/1.12.zip)解压到用户文件夹/.cache/MCPMappingViewer下，我这里配置了1.12版本的snapshot_20180802。最近也打算把这个工具汉化了然后顺便挂一份文件到自己服务器上。

另外，作者的网站会自动更新每日的mapping下载，http://export.mcpbot.bspk.rs/。

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
