### ISSUE TITLE
Minecraft 1.12的Gameregistey问题

### ISSUE THREAD

**Issue by zmz2333** [ustc-zzzz/fmltutor#86]
我记得大佬有在fmltutor里面提及过这个1.9之后版本的register问题，但是没有教怎么修改，所以来问一下，
![3 7p69ob ll3q 6lbypud0](https://user-images.githubusercontent.com/31442946/44088532-05e7bea6-9ff6-11e8-8334-5a23dac0fd19.png)
233

**Comment by chinese-wzq** [comment]
对呀，我也是有问题的QAQ，都不知道怎么解决

**Comment by FirokOtaku** [comment]
ctrl+单击, 跳到方法定义, 找方法都有啥参数然后传一个试试就行了啊

**Comment by chinese-wzq** [comment]
刚入门，看不懂语法啊

**Comment by FirokOtaku** [comment]
java刚入门? 如果是java刚入门, 那先别做mod了(认真的)
先回去好好学java再说, 要不然你会很吃力, 遇到坑就抓瞎

**Comment by cvrunmin** [comment]
參考[本頁面](https://mcforge-cn.readthedocs.io/zh/latest/concepts/registries/)

**Comment by zmz2333** [comment]
![fw dp14afx8x f 8e9t17](https://user-images.githubusercontent.com/31442946/44943207-f93dc300-adf4-11e8-9499-dfe9b2fbfc70.png)
已经解决了，改成这个
![ehi 0w31u3 y twkcsvddqs](https://user-images.githubusercontent.com/31442946/44943216-1b374580-adf5-11e8-9b4e-33ff0af9ef6a.png)
就可以了

[参考来自hookan]https://blog.hookan.top/2017/12/25/forge1/

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
