### ISSUE TITLE
有1.12.2的教程吗？急求！

### ISSUE THREAD

**Issue by ghost** [ustc-zzzz/fmltutor#87]
有1.12.2的教程吗？急求！

**Comment by 0f-0b** [comment]
[Mod开发教程 - 编程开发](http://www.mcbbs.net/forum.php?mod=forumdisplay&fid=479&filter=typeid&typeid=1028)

此外，
> 本教程也会考虑到诸如Minecraft 1.9.4、1.10.2、1.11.2等更高的Minecraft版本对应的Forge版本，并尽可能使相同的代码在高版本的Forge里正常工作，但不作保证。
> \- [0-绪论 § 源代码](https://fmltutor.ustc-zzzz.net/0-绪论.html#源代码)

**Comment by FirokOtaku** [comment]
然而已经咕了2333

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
