### ISSUE TITLE
2.2.1 新的工具 中建议添加

### ISSUE THREAD

**Issue by huangluyu** [ustc-zzzz/fmltutor#9]
ToolMaterial中建议添加下文代码的提醒：

ItemLoader.java中
**_public static final Item.ToolMaterial REDSTONE = EnumHelper.addToolMaterial("REDSTONE", 3, 16, 16.0F, 0.0F, 10);_**
必须放到
_**public static ItemPickaxe redstonePickaxe = new ItemRedstonePickaxe();**_
之前，否则会报错。

**Comment by ustc-zzzz** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8004211/15275354/f04e2b06-1afb-11e6-922f-ad68267d1cc8.png)
已更新。
