### ISSUE TITLE
MC Forge 从1.13版本开始有很大变化

### ISSUE THREAD

**Issue by xianfengting** [ustc-zzzz/fmltutor#91]
比如，

- 安装MDK时不用再执行./gradlew setupDecompWorkspace，直接IDE导入项目（不过因为才出来没一个月，官方也没更新教程，所以具体是什么我也不清楚）。
- 支持了Java10及以上Java版本，和Gradle 4.9。

当然作者这个教程是不是针对1.13版本，我只是希望作者在教程里加一条注意事项，就是1.13以上的Forge版本根现在相比变了很多，至于具体哪些变了还要等官方教程或公告更新，今年3月份才出的1.13 Forge。

**Comment by AMIRIOX** [comment]
是的, 
> 安装MDK时不用再执行./gradlew setupDecompWorkspace，直接IDE导入项目, 

我就是在这个上踩坑了.
但是IDEA导入项目仍然很慢(Download xxx.pom),呜呜

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
