### ISSUE TITLE
请问这种问题该怎么解决呢？

### ISSUE THREAD

**Issue by lzby-42** [ustc-zzzz/fmltutor#93]
![TIM截图20190331162551](https://user-images.githubusercontent.com/49115240/55286715-1447d400-53d2-11e9-9f7b-5e40fd580a0a.png)

**Comment by 0f-0b** [comment]
在 `gradle.properties` 文件（不存在则创建）中添加一行 `org.gradle.daemon=false` 禁用 Gradle daemon。
根本原因是内存不足。

**Comment by lzby-42** [comment]
嗷哦，谢谢大佬解答：D

**Comment by lzby-42** [comment]
> 嗷哦，谢谢大佬解答：d



> 在`gradle.properties`文件（不存在则创建）中添加一行`org.gradle.daemon=false`禁用Gradle守护进程。
> 根本原因是内存不足。
嗷哦，谢谢大佬解答：D

**Comment by lzby-42** [comment]
> 在`gradle.properties`文件（不存在则创建）中添加一行`org.gradle.daemon=false`禁用Gradle守护进程。
> 根本原因是内存不足。

![TIM截图20190404192122](https://user-images.githubusercontent.com/49115240/55552108-06b28700-570f-11e9-82bc-bd1729daf05d.png)
emmm，新的问题又来了，

**Comment by 0f-0b** [comment]
仍然是因为内存不足……

`gradle.properties`:

```properties
org.gradle.daemon=true
org.gradle.jvmargs=-Xms1440M
```

如果还出错，那么可以自行调整 `1440M` 这个数值。

> 由于获取反编译的Minecraft源代码的过程是在自己的计算机上进行的，所以说有时可能出现内存不足的情况。如果运行一次后出现的错误中有`Java Heap Space`的字样，那很可能是因为默认情况下分配的内存不足。这时你可以添加下面的参数手动指定JVM的初始内存，同时禁用[Gradle Daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html)以减少不必要的内存消耗（当然，减少计算机上的其他不必要进程以提高内存可用空间也很重要）。经过作者测试，1.4G的内存足够反编译Minecraft了。
> \- [1.1 配置你的工作环境 § 配置工作环境](https://fmltutor.ustc-zzzz.net/1.1-配置你的工作环境.html#配置工作环境)

**Comment by lzby-42** [comment]
> 仍然是因为内存不足……
> 
> `gradle.properties`:
> 
> ```ini
> org.gradle.daemon=true
> org.gradle.jvmargs=-Xms1440M
> ```
> 
> 如果还出错，那么可以自行调整 `1440M` 这个数值。
> 
> > 由于获取反编译的Minecraft源代码的过程是在自己的计算机上进行的，所以说有时可能出现内存不足的情况。如果运行一次后出现的错误中有`Java Heap Space`的字样，那很可能是因为默认情况下分配的内存不足。这时你可以添加下面的参数手动指定JVM的初始内存，同时禁用[Gradle Daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html)以减少不必要的内存消耗（当然，减少计算机上的其他不必要进程以提高内存可用空间也很重要）。经过作者测试，1.4G的内存足够反编译Minecraft了。
> > - [1.1 配置你的工作环境 § 配置工作环境](https://fmltutor.ustc-zzzz.net/1.1-%E9%85%8D%E7%BD%AE%E4%BD%A0%E7%9A%84%E5%B7%A5%E4%BD%9C%E7%8E%AF%E5%A2%83.html#%E9%85%8D%E7%BD%AE%E5%B7%A5%E4%BD%9C%E7%8E%AF%E5%A2%83)

谢谢，我去试试：）

**Comment by lzby-42** [comment]
> 仍然是因为内存不足......
> 
> `gradle.properties`：
> 
> ```ini
> org.gradle.daemon = true
>  org.gradle.jvmargs = -Xms1440M
> ```
> 
> 如果还出错，可以那么调整自行`1440M`这个数值。
> 
> > 由于获取反编译的的Minecraft源代码的过程是在自己的计算机上进行的，所以说有时可能出现内存不足的情况。如果运行一次后出现的错误中有`Java Heap Space`的字样，那很可能是因为默认情况下分配的内存不足。这时你可以添加下面的参数手动指定JVM的初始内存，同时禁用[Gradle Daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html)以减少不必要的内存消耗（当然，减少计算机上的其他不必要进程以提高内存可用空间也很重要） 。经过作者测试，1.4G的内存足够反编译Minecraft了。
> > - [1.1配置你的工作环境§配置工作环境](https://fmltutor.ustc-zzzz.net/1.1-%E9%85%8D%E7%BD%AE%E4%BD%A0%E7%9A%84%E5%B7%A5%E4%BD%9C%E7%8E%AF%E5%A2%83.html#%E9%85%8D%E7%BD%AE%E5%B7%A5%E4%BD%9C%E7%8E%AF%E5%A2%83)

谢谢大佬，不过我用另一个”方法“解决了（设置一个64位的虚拟机。在虚拟机里构建。可以正常构建完成接，下来只要把C:\Users\Administrator.USER\.gradle整个文件夹和配置的mdk源文件文件夹一同复制进物理机中就可以了。

**Comment by ustc-zzzz** [comment]
本教程由于严重过时，故放弃更新，请检索仍在更新的教程。
