### ISSUE TITLE
TileEntity update 函数问题

### ISSUE THREAD

**Issue by AqourSoro** [ustc-zzzz/fmltutor#94]
update中判断ItemStack ！= null 是不是应该是 ItemStack != ItemStack.EMPTY? 1.12.2里get一个ItemStack的时候好像不会得到null。。。

**Comment by 3TUSK** [comment]
1. 该教程面向 1.8.9。
2. ***请不要直接 `itemStack != ItemStack.EMPTY`！！！！！正确的做法是 `!itemStack.isEmpty()`！！！！！***
